In [1]:
from numpy.random import randn
import numpy as np

data = randn(2,3)
data

array([[ 0.70516643, -1.18711046,  1.02409864],
       [-1.14557659, -1.2616279 ,  0.33449412]])

In [2]:
data * 2

array([[ 1.41033286, -2.37422092,  2.04819729],
       [-2.29115318, -2.5232558 ,  0.66898824]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data + data

array([[ 1.41033286, -2.37422092,  2.04819729],
       [-2.29115318, -2.5232558 ,  0.66898824]])

In [5]:
data.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [6]:
data.shape

(2, 3)

In [7]:
data.strides

(24, 8)

In [8]:
data.ndim

2

In [9]:
data.data

In [10]:
data.size

6

In [11]:
data.itemsize

8

In [12]:
data.nbytes

48

In [13]:
data.base