<a href="https://colab.research.google.com/github/zzhining/python_basic/blob/master/python_basic_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 3928
y = 500
z = 100

print("500원짜리 동전: {}개".format(x//y))

500원짜리 동전: 7개


In [ ]:
import math

a = 21.9
b = 37
c = 13.6

(a+b+c)/3

24.166666666666668

In [ ]:
L = [1, 3, 5, 7, 9]
L.append(L[0])
L.pop(0)
print(L)

[3, 5, 7, 9, 1]


In [ ]:
L = [1, 3, 5, 7, 9]
L1 = []

for i in range(len(L)):
    if i < len(L) - 1:
        L1.append(L[i+1])
    else:
        L1.append(L[0])
    
print(L1)

[3, 5, 7, 9, 1]


In [ ]:
import numpy as np 

# m=np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]]) 
# f=np.array([[2,0,1],[0,1,2],[1,0,2]]) 
m=np.array([[0,0,0,0,0],[0,5,2,1,0],[0,3,0,2,0],[0,1,2,4,0],[0,0,0,0,0]]) 
f=np.array([[1,0],[3,2]]) 
result=[]


mx,my=np.shape(m) 
fx,fy=np.shape(f) 

for i in range(mx-fx+1): 
    for j in range(my-fy+1): 
        result.append((m[i:i+fy,j:j+fy]*f).sum()) 
result=np.array(result).reshape(4,4) 
print(result)


[[10 19  8  3]
 [ 6 14  6  7]
 [ 2 10 14 14]
 [ 0  1  2  4]]


In [ ]:
np.mean(np.array([2,3,6,7]))

4.5

In [ ]:
n = input("수식 입력(예: 20 * 40) :")

n_arr = n.split()
n1 = float(n_arr[0])
x1 = str(n_arr[1])
n2 = float(n_arr[2])

if(x1 =="+"):
    print("%9.6f + %9.6f =" %(n1, n2), "%9.6f" %(n1+n2))
elif(x1 =="-"):
    print("%9.6f - %9.6f =" %(n1, n2), "%9.6f" %(n1-n2))
elif(x1 =="*"):
    print("%9.6f * %9.6f = " %(n1, n2), "%8.6f" %(n1*n2))
elif(x1 =="/"):
    if(n2 == 0):
        print("%9.9f 로 나누기를 수행할 수 없습니다." %0)
    else:
        print("%9.6f / %9.6f =" %(n1, n2), "%8.6f" %(n1/n2))
else:
    print("%s 지원하지 않는 연산자입니다." %x1)

수식 입력(예: 20 * 40) :20 + 4
20.000000 +  4.000000 = 24.000000


In [ ]:
def solution(info, lecture, qty):
    code = 0 
    
    # 코드를 작성하시오.
    
    return code, info 

In [ ]:
info = {'수업1' : [10, 20], '수업2' : [6, 6], '수업3' : [27,50], '수업4' : [10, 20]}

def solution(info, lecture, qty):
    code = 0 
    try :    
        registered, total = info[lecture]
        if registered + qty > total:
            code = 1
        else:
            info[lecture] = [registered + qty, total]
    except:
        code = 1
    return code, info 


In [ ]:
solution(info, '수업1', 2)

(0, {'수업1': [12, 20], '수업2': [6, 6], '수업3': [27, 50], '수업4': [10, 20]})

In [ ]:
solution(info, '수업5', 2)

(1, {'수업1': [10, 20], '수업2': [6, 6], '수업3': [27, 50], '수업4': [10, 20]})

In [ ]:
solution(info, '수업2', 2)

(1, {'수업1': [10, 20], '수업2': [6, 6], '수업3': [27, 50], '수업4': [10, 20]})

In [ ]:
fruit = {'배' : [2, 1000], '자몽' : [1, 2000], '메론' : [1, 8000], '감' : [6, 800]}
f = input("먹고 싶은 과일은? :")

try :    
    num, price = fruit[f]
    print(f +' 맛있게 드세요')
    fruit[f] = [num-1, price]
except:
    print(f +' 준비되어 있지 않습니다')

total = 0
for num, price in fruit.values():
    if num < 5:
        total += price * (5 - num)
print('각 과일 당 최소 5개는 되도록 구입합니다')
print('구입에 필요한 총 금액은 : {} 원 입니다'.format(total))

먹고 싶은 과일은? :메론
메론 맛있게 드세요
각 과일 당 최소 5개는 되도록 구입합니다
구입에 필요한 총 금액은 : 51000 원 입니다


In [ ]:
num = input('구하려는 소수의 개수를 입력:')
x = int(num)
primeChk = True
n = 2

while x > 0:
    for i in range(2, n):
        if n % i == 0:
            primeChk = False
            break
    if primeChk:
        print(n)
        x = x - 1
    n = n + 1
    primeChk = True
print('{} 개의 소수를 찾았습니다'.format(num))

구하려는 소수의 개수를 입력:11
2
3
5
7
11
13
17
19
23
29
31
11 개의 소수를 찾았습니다


In [ ]:
pluse_list = []
minus_list = []
numbers = input('정수들을 입력 :')
num_list = numbers.split(' ')

try:
    for i in num_list:
        if int(i) > 0 :
            pluse_list.append(int(i))
        elif int(i) < 0:
            minus_list.append(int(i))
except:
    print('입력한 숫자가 없습니다')
                
print('양수: {}개, 음수: {}개, 합계: {}'.format(len(pluse_list), len(minus_list), sum(pluse_list) + sum(minus_list)))        

정수들을 입력 :
입력한 숫자가 없습니다
양수: 0개, 음수: 0개, 합계: 0


In [ ]:
pluse_list = []
minus_list = []
numbers = input('정수들을 입력:\n')

try:    
    # 입력으로부터 정수 리스트로 변환하는 것은 한 줄 코드로 작성
    num_list = [int(i) for i in numbers.split(' ')]
    for i in num_list:
        if i > 0 :
            pluse_list.append(i)
        elif i < 0:
            minus_list.append(i)
except:
    print('입력한 숫자가 없습니다')
                
print('양수: {}개, 음수: {}개, 합계: {}'.format(len(pluse_list), len(minus_list), sum(pluse_list) + sum(minus_list)))        

정수들을 입력:
23 -2 5 89 -43 0 5 0
양수: 4개, 음수: 2개, 합계: 77


In [ ]:
def password_validcheck(pwd):
    if len(pwd) < 8 or len(pwd) > 14:
        print("error! 8 글자 이상이어야 함")
        return False

    num = 0
    alpha = 0
    for char_num in pwd:
        if char_num.isalnum() == False:
            print("error! 영문자, 숫자로만 구성되어야함")
            return False
        if char_num.isalpha():
            num += 1
        else:            
            alpha += 1

    if num == 0:
        print("error! 영문도 포함되어야 함")
        return False

    if alpha == 0:
        print("error! 숫자도 포함되어야 함")
        return False

    if num < 2:
        print("error! 최소한 2개의 숫자를 포함해야 함")
        return False  

    print("Valid password")
    return True
    

for i in range(5):
    pwd = input("Enter password: ")
    if password_validcheck(pwd):
        break

Enter password: SogangUniv
error! 숫자도 포함되어야 함
Enter password: 123456789
error! 영문도 포함되어야 함
Enter password: songang12
Valid password


In [ ]:
formula = input('수식 입력(예: 20 * 40):')
formula_list = formula.split(' ')
a = float(formula_list[0])
b = float(formula_list[2])
op = formula_list[1]
if op == '+':
    print('{:.6f} + {:.6f} = {:.6f}'.format(a, b, a+b))
elif op == '-':
    print('{:.6f} - {:.6f} = {:.6f}'.format(a, b, a-b))
elif op == '*':
    print('{:.6f} * {:.6f} = {:.6f}'.format(a, b, a*b))
elif op == '/':
    if b == 0:
        print('{:.6f}로 나누기를 수행할 수 없습니다'.format(b))
    else:
        print('{:.6f} / {:.6f} = {:.6f}'.format(a, b, a/b))
else:
    print('{} 지원하지 않는 연산자입니다'.format(op))

수식 입력(예: 20 * 40):30 / 0
0.000000로 나누기를 수행할 수 없습니다


In [ ]:
import random 

def getPercent(num):
    cnt=[0,0] 
    for i in range(num):
        cnt[0] += random.randint(0,1)
        if i < 10:
            print('{:>3} 번째까지 던지기에서 앞면이 나올 확률 : {:.0f}%'.format(i + 1, cnt[0] / (i + 1) * 100))
        elif i % 10 == 9:
            print('{:>3} 번째까지 던지기에서 앞면이 나올 확률 : {:.0f}%'.format(i + 1, cnt[0] / (i + 1) * 100))
    return cnt[0]

if __name__ == "__main__":	
    num = int(input('동전 던지기 시도 횟수를 입력(1 ~ 100) : '))

    count = getPercent(num)

    print('\n**********************************************')
    print('총 {}번 동전 던지기에서 앞면이 나올 확률: {:.0f}%'.format(num, count/num * 100 ))


동전 던지기 시도 횟수를 입력(1 ~ 100) : 65
  1 번째까지 던지기에서 앞면이 나올 확률 : 0%
  2 번째까지 던지기에서 앞면이 나올 확률 : 0%
  3 번째까지 던지기에서 앞면이 나올 확률 : 33%
  4 번째까지 던지기에서 앞면이 나올 확률 : 25%
  5 번째까지 던지기에서 앞면이 나올 확률 : 40%
  6 번째까지 던지기에서 앞면이 나올 확률 : 50%
  7 번째까지 던지기에서 앞면이 나올 확률 : 43%
  8 번째까지 던지기에서 앞면이 나올 확률 : 50%
  9 번째까지 던지기에서 앞면이 나올 확률 : 56%
 10 번째까지 던지기에서 앞면이 나올 확률 : 60%
 20 번째까지 던지기에서 앞면이 나올 확률 : 45%
 30 번째까지 던지기에서 앞면이 나올 확률 : 43%
 40 번째까지 던지기에서 앞면이 나올 확률 : 45%
 50 번째까지 던지기에서 앞면이 나올 확률 : 48%
 60 번째까지 던지기에서 앞면이 나올 확률 : 50%

**********************************************
총 65번 동전 던지기에서 앞면이 나올 확률: 51%


동전 던지기 시도 횟수를 입력(1 ~ 100) : 50
  1 번째까지 던지기에서 앞면이 나올 확률 : 100%
  2 번째까지 던지기에서 앞면이 나올 확률 : 100%
  3 번째까지 던지기에서 앞면이 나올 확률 : 67%
  4 번째까지 던지기에서 앞면이 나올 확률 : 50%
  5 번째까지 던지기에서 앞면이 나올 확률 : 60%
  6 번째까지 던지기에서 앞면이 나올 확률 : 67%
  7 번째까지 던지기에서 앞면이 나올 확률 : 57%
  8 번째까지 던지기에서 앞면이 나올 확률 : 50%
  9 번째까지 던지기에서 앞면이 나올 확률 : 44%
 10 번째까지 던지기에서 앞면이 나올 확률 : 40%
 20 번째까지 던지기에서 앞면이 나올 확률 : 45%
 30 번째까지 던지기에서 앞면이 나올 확률 : 50%
 40 번째까지 던지기에서 앞면이 나올 확률 : 45%
 50 번째까지 던지기에서 앞면이 나올 확률 : 42%

**********************************************
총 50번 동전 던지기에서 앞면이 나올 확률: 42%
